### ISSUE TITLE
Create a detailed breakdown of the tasks

### ISSUE THREAD

**Issue by DonaldHesler** [kshep425/ALUM-APP#9]
This detailed break down should show what sections of the app each person are developing. This should be project into a schedule to keep people on track. The progress should be tracked using issues.

**Comment by SkinnySk8ter** [comment]
3/14/2020

Jody - drawing workflow diagrams to organize workflow

Jordyn -making wireframe to get a visual image of the page

Keisha -drawing workflow diagrams/learning firebase

Should have a basic understanding of what is expected for the end goal by the end of the day.

**Comment by kshep425** [comment]
1st week ending 3/14/2020 - setting deadlines/project flow
Figure out roles to complete certain tasks
	Keisha - Login, Membership Registration, Donations
	Jordyn - HomePage, Event Page
	Jody - Webmaster, About Page
Understand what the page should look like
Understand what the page should be able to do
Research eventbrite, sprite, node sdk, research api
Gather photos to use on site

2nd week ending 3/21/2020 - MVP Quality Check
Have a working presentation that does SOMETHING - doesn’t need to be fully running...just have a basic layout of what is expected
Good place to see what you have vs what is needed

3rd week ending 3/28/2020 - Final plan before project presentation 
Project should be close to being finished
Use this time to polish the code and site
Does the site work? (does it perform the basic functions? Is it still broken?)

4th week ending 4/4/2020 - Presentation week
Project should be up and running 
Finalizing the polish of the application
Basic / complicated functionality should be up and running
Be able to explain future functionality of the app


Also look in Glo, in Github, and the google doc.
